INSERT INTO TB_PLAYER_POSITION (NAME) VALUES ('Goalkeeper');
INSERT INTO TB_PLAYER_POSITION (NAME) VALUES ('Defender');
INSERT INTO TB_PLAYER_POSITION (NAME) VALUES ('Midfielder');
INSERT INTO TB_PLAYER_POSITION (NAME) VALUES ('Forward');

INSERT INTO TB_CATEGORIES (NAME) VALUES ('Under 15');
INSERT INTO TB_CATEGORIES (NAME) VALUES ('Under 17');
INSERT INTO TB_CATEGORIES (NAME) VALUES ('Under 20');
