INSERT INTO TB_PLAYER_POSITION (NAME) VALUES ('Goalkeeper');
INSERT INTO TB_PLAYER_POSITION (NAME) VALUES ('Defender');
INSERT INTO TB_PLAYER_POSITION (NAME) VALUES ('Midfielder');
INSERT INTO TB_PLAYER_POSITION (NAME) VALUES ('Forward');

INSERT INTO TB_CATEGORIES (NAME) VALUES ('Under 15');
INSERT INTO TB_CATEGORIES (NAME) VALUES ('Under 17');
INSERT INTO TB_CATEGORIES (NAME) VALUES ('Under 20');

INSERT INTO TB_ADDRESS_ATHLETE (STREET, LOCAL_NUMBER, COMPLEMENT,ZIP_CODE, NEIGHBORHOOD, CITY, STATE, COUNTRY) VALUES ('123 Main St', '456', 'Apt 789', '12345-678', 'Downtown', 'Metropolis', 'NY', 'USA');
INSERT INTO TB_ADDRESS_ATHLETE (STREET, LOCAL_NUMBER, COMPLEMENT,ZIP_CODE, NEIGHBORHOOD, CITY, STATE, COUNTRY) VALUES ('456 Elm St', '101', '', '23456-789', 'Uptown', 'Gotham', 'NJ', 'USA');


INSERT INTO TB_PERSONAL_DOCUMENTS (CPF, RG, PASSPORT, BIDCBF) VALUES ('123.456.789-00', 'MG-12.345.678', 'P1234567', 'BID123456');

INSERT INTO TB_CONTRACTS (HAS_CONTRACT, SALARY,DURATION, START_DATE, END_DATE, CONTRACT_PDF, CONTRACT_TYPE) VALUES (true, 50000.00, 24, '2023-01-01', '2024-12-31', 'contract1.pdf', 1);
INSERT INTO TB_CONTRACTS (HAS_CONTRACT, SALARY,DURATION, START_DATE, END_DATE, CONTRACT_PDF, CONTRACT_TYPE) VALUES (true, 30000.00, 12, '2023-06-01', '2024-05-31', 'contract2.pdf', 1);